version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${HOME}/.postgresql/root.crt:/tmp/keys/keyfile.json:ro